import Head from "next/head"
import Sidebar from "./Sidebar"

export default function Layout(props) {
  return (
    <>
      <Head>
        <title>ChessCongress.app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <main className="ml-64 p-12">{props.children}</main>
    </>
  )
}
